@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tconstruct.smeltery.inventory;

import mcp.MethodsReturnNonnullByDefault;

import org.jetbrains.annotations.ParametersAreNonnullByDefault;
