# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
systemProp.http.connectionTimeout=120000
systemProp.http.socketTimeout=120000
systemProp.https.connectionTimeout=120000
systemProp.https.socketTimeout=120000

mod_version=3.11.2

# Minecraft Version Information
minecraft_base_version=1.21
minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)

# NeoForge Version Information
neo_version=21.1.228
loader_range=[4,)
neo_range=[21.1.0,)
parchment_version=2024.11.17

# Build Dependencies
mantle_version=1.11.108
mantle_range=[1.11.108,)

# Optional compat
jei_version=19.27.0.340
jei_range=[19.0.0,)
#probe_version=5.1.0
#crt_version=7.1.0.307
#crt_range=[7.1.0.245,)
ie_version=9.4.0-166.40
json_things_version=0.9.9
json_things_range=[0.9.9,)
