name: 1.12 Issue Report
description: Report an issue with the 1.12 version of Minecraft
labels: [1.12, Bug, Unreviewed]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following template to report your issue. Please note that 1.12 development is mostly finished, so unless the issue is trivial to fix or is critical, it is unlikely to be dealt with. If we have to debug the issue ourselves it will not be fixed.
  
  - type: markdown
    attributes:
      value: "## Versions"
  
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      value: 1.12.2
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      placeholder: "Ex: 14.23.5.2855"
    validations:
      required: true
  - type: input
    id: mantle-version
    attributes:
      label: Mantle Version
    validations:
      required: true
  - type: input
    id: tinkers-version
    attributes:
      label: "Tinkers' Construct Version"
      description: "'Latest' is not a valid answer, write an exact version number"
    validations:
      required: true
  
  
  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true
  
  - type: input
    id: crash-report
    attributes:
      label: Crash Report
      description: Paste a link to the crash report, if present
    validations:
      required: false
      
  - type: dropdown
    id: tinkers-only
    attributes:
      label: "Reproduced with only Tinkers' Construct?"
      description: "We expect you to test with just Tinkers' Construct and Mantle, answering 'Yes' means you have tested and confirmed the issue with no other mods."
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
      
  - type: textarea
    id: required-mods
    attributes:
      label: Other mods required
      description: If you answered "No" above, list other mods required to reproduce this. Should be less than 10 mods.
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirm the following
      description: Check all actions you have performed
      options:
        - label: "Confirm you have searched the tracker to see if your issue already exists"
        - label: "Confirm you are not using performance enhancers, such as optifine"
        - label: "Confirm you have tested without external core mods/mixins"
