name: 1.18 Issue Report
description: Report an issue with the 1.18 alphas of Minecraft
labels: [1.18, Bug, Unreviewed]
body:
  - type: markdown
    attributes:
      value: |
        Please note that 1.18 versions of the mod are in alpha, so are subject to change. Before submitting an issue, please search the following links to make sure your issue is not covered:
        
        * **[Roadmap](/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-Roadmap)**: Discusses unimplemented features and planned new changes
        * **[What's New](/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3)**: Discusses many of the major changes in the 1.18 alphas
        * **[FAQ](/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ)**: Answers to many frequently asked questions about the 1.18 versions
        
        Please fill in the following template to report your issue.
        
  - type: markdown
    attributes:
      value: "## Versions"
  
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      value: 1.18.1
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      placeholder: "Ex: 36.1.0"
    validations:
      required: true
  - type: input
    id: mantle-version
    attributes:
      label: Mantle Version
    validations:
      required: true
  - type: input
    id: tinkers-version
    attributes:
      label: "Tinkers' Construct Version"
      description: "'Latest' is not a valid answer, write an exact version number"
    validations:
      required: true
  
  
  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true
  
  - type: input
    id: crash-report
    attributes:
      label: Crash Report
      description: Paste a link to the crash report, if present
    validations:
      required: false
      
  - type: dropdown
    id: tinkers-only
    attributes:
      label: "Reproduced with only Tinkers' Construct?"
      description: "We expect you to test with just Tinkers' Construct and Mantle, answering 'Yes' means you have tested and confirmed the issue with no other mods."
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
      
  - type: textarea
    id: required-mods
    attributes:
      label: Other mods required
      description: If you answered "No" above, list other mods required to reproduce this. Should be less than 10 mods.
    validations:
      required: false
  
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirm the following
      description: Check all actions you have performed
      options:
        - label: "Check if you are using performance enhancers, such as optifine"
        - label: "Check if you have searched the tracker to see if your issue already exists, notably pinned issues"
        - label: "Check if you did not read any of the checkboxes and just checked all the boxes"
        - label: "Check if you read FAQ to see if your issue is answered"
