@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tconstruct.smeltery.recipe;

import mcp.MethodsReturnNonnullByDefault;

import org.jetbrains.annotations.ParametersAreNonnullByDefault;
